.\" x-roff document
.do mso man.tmac
.TH kv 1 2017-05-09 GNU
.PP
.SH NAME
kv - a simple flat file key value store.
.PP
.SH SYNOPSIS
kv [\fIOPTION\fP]...[\fIFILE\fP]...
.PP
.SH DESCRIPTION
\fIkv\fP provides an interface for storing, retrieving and deleting key-value pairs stored in json encoded flat files. Its usage is aimed towards shell scripts and command line driven environments.
.PP
.SH OPTIONS
.TP
\fB-d, --delete
\fRdelete a key in the database
.PP
.TP
\fB-f, --format
\fRspecify a format string;%k and %v are placeholders for key and value respectively
.PP
.TP
\fB-h, --help
\fRdisplays a short-help text and exits
.PP
.TP
\fB-l, --list
\fRlist couples of key and values
.PP
.TP
\fB-k, --key
\fRdisplay value of this key or update the key if --value is specified
.PP
.TP
\fB-v, --value
\fRupdate or set a key in the database
.PP
.TP
\fB-V, --version
\fRdisplays the program version, copyright and license information and exists.
.PP
.SH EXAMPLE
Record a new key-value pair.
.RS 4
.EX

$ kv -k kv_location -v /home/user/.local/bin/ /home/user/.cache/kv.db

.EE
.RE
.PP
Get the value of a record
.RS 4
.EX

$ kv -k kv_location /home/user/.cache/kv.db

.EE
.RE
.PP
List all records and print them with a custom format
.RS 4
.EX

$ kv -l -f "%k -- %v" /home/user/.cache/kv.db

.EE
.RE
.PP
.SH COPYRIGHT
Copyright (C) 2017 Free Software Foundation, Inc. License GPLv3+: GNU GPL version 3 or later (http://gnu.org/licenses/gpl.html). This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
.PP
.SH AUTHOR
Written by Francesco Mecca (me@francescomecca.eu).
